# Generated by Django 4.2.5 on 2023-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержимое письма')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Рассылка писем',
                'verbose_name_plural': 'Рассылки писем',
            },
        ),
    ]
