# Generated by Django 4.2.5 on 2023-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_senders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsender',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
