# Generated by Django 4.2.5 on 2023-11-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_senders', '0002_mailsender_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailsender',
            options={'verbose_name': 'Рассыльщик', 'verbose_name_plural': 'Рассыльщики'},
        ),
    ]
