# Generated by Django 4.2.5 on 2023-11-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_sum_old_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_receive_mails',
            field=models.BooleanField(default=True, verbose_name='Получать рассылку'),
        ),
    ]
