# Generated by Django 4.2.5 on 2024-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='article',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Артикул'),
        ),
    ]
