# Generated by Django 4.2.5 on 2023-09-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='article',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Артикул'),
        ),
    ]
